"""Create initial tables for PostgreSQL

Revision ID: e2398e8ed0c5
Revises: 
Create Date: 2025-07-22 17:38:26.900231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2398e8ed0c5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.String(), nullable=True),
    sa.Column('chemistry', sa.String(), nullable=True),
    sa.Column('rated_capacity', sa.Float(), nullable=True),
    sa.Column('configuration', sa.String(), nullable=True),
    sa.Column('assembly_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('znbr_molarity', sa.Float(), nullable=True),
    sa.Column('teacl_molarity', sa.Float(), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.Column('cycle_no', sa.Integer(), nullable=True),
    sa.Column('current_density', sa.Float(), nullable=True),
    sa.Column('charge_V', sa.Float(), nullable=True),
    sa.Column('discharge_V', sa.Float(), nullable=True),
    sa.Column('capacity_mAh', sa.Float(), nullable=True),
    sa.Column('pH', sa.Float(), nullable=True),
    sa.Column('csv_path', sa.String(), nullable=True),
    sa.Column('ce_pct', sa.Float(), nullable=True),
    sa.Column('delta_V', sa.Float(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycles')
    op.drop_table('cells')
    # ### end Alembic commands ###
